[package]
name = "lnl-fibonacci"
version = "0.1.0"
edition = "2021"
authors = ["Rick Burta <rick@rickburta.ca>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
